mural_dbt:
  target: dev #default target when unspecified and will be used for local development
  outputs:
    dev:
      type: redshift
      threads: 8
      host: "{{ env_var('DBT_HOST') }}"
      user: "{{ env_var('DBT_USER') }}"
      pass: "{{ env_var('DBT_PASSWORD') }}"
      port: "{{ env_var('DBT_PORT') | as_number }}"
      dbname: "{{ env_var('DBT_DATABASE') }}"
      schema: analytics

    docs:
      type: redshift
      threads: 8
      host: "{{ env_var('DBT_HOST') }}"
      user: "{{ env_var('DBT_USER') }}"
      pass: "{{ env_var('DBT_PASSWORD') }}"
      port: "{{ env_var('DBT_PORT') | as_number }}"
      dbname: "{{ env_var('DBT_DATABASE') }}"
      schema: analytics
