name: dbt-testing-current

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: DBT CI
    runs-on: ubuntu-latest
    env:
      DBT_PROFILES_DIR: ./
      DBT_HOST: ${{ secrets.DBT_HOST }}
      DBT_USER: ${{ secrets.DBT_USER }}
      DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
      DBT_PORT: ${{ secrets.DBT_PORT }}
      DBT_DATABASE: ${{ secrets.DBT_DATABASE }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install dbt-redshift
          dbt deps

      - name: Compile models
        run: dbt compile

      - name: Build catalog
        run: dbt docs generate