name: Compile and Generate Catalog

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Main CI
    runs-on: ubuntu-latest
    env:
      DBT_USER: ${{ secrets.DBT_USER }}
      DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
      DBT_DATABASE: ${{ secrets.DBT_DATABASE }}
      DBT_PROFILES_DIR: ..
      DBT_REDSHIFT_ACCOUNT: ${{ secrets.DBT_HOST }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: compile
        uses: datacoves/dbt-coves-action@v1
        with:
          command: "dbt compile --full-refresh --profiles-dir .. --project-dir .."

      - name: build-catalog
        uses: datacoves/dbt-coves-action@v1
        with:
          command: "dbt docs generate"
